# Generated by Django 3.2 on 2023-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposium', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='point',
            name='model_link',
        ),
        migrations.RemoveField(
            model_name='exhibition_entry',
            name='research_paper',
        ),
        migrations.AddField(
            model_name='exhibition_entry',
            name='research_paper_link',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.AlterField(
            model_name='exhibition_entry',
            name='explanation_video_link',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.DeleteModel(
            name='Model_All',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
